import '@/styles/globals.css'
import Head from 'next/head'
import type { AppProps } from 'next/app'

function App({ Component, pageProps }: AppProps) {
  <Head>
        <title>NewsApp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
  </Head>
  
  return <Component {...pageProps} />
}

export default App